import type { CharacterDef, CharacterId } from '../types.ts'

export const characters: Record<CharacterId, CharacterDef> = {
  kael: {
    id: 'kael',
    name: 'Kael Voss',
    title: 'Festival Duelist',
    joinLevel: 1,
    base: { hp: 52, mp: 14, atk: 13, def: 8, mag: 5, spd: 12 },
    growth: { hp: 8, mp: 2, atk: 2, def: 1, mag: 1, spd: 1 },
    techs: ['cyclone', 'arc-slash', 'sever'],
    weapon: 'practice-blade',
    armor: 'kael-cloth',
    sprite: 'kael',
    portrait: 'kael',
    color: '#d4543c',
    blurb: 'A fairground duelist who treats a late clock as a personal insult.',
  },
  mira: {
    id: 'mira',
    name: 'Mira Quell',
    title: 'Ash Archivist',
    joinLevel: 2,
    base: { hp: 40, mp: 24, atk: 7, def: 6, mag: 15, spd: 11 },
    growth: { hp: 6, mp: 3, atk: 1, def: 1, mag: 2, spd: 1 },
    techs: ['kindle', 'needle', 'mend', 'read', 'bolt'],
    weapon: 'field-bow',
    armor: 'mira-cloak',
    sprite: 'mira',
    portrait: 'mira',
    color: '#2a9d8f',
    blurb: 'An archivist from the ash age who came to see which clocks still move.',
  },
  torin: {
    id: 'torin',
    name: 'Torin Hale',
    title: 'Crown Knight',
    joinLevel: 4,
    base: { hp: 68, mp: 16, atk: 14, def: 12, mag: 7, spd: 8 },
    growth: { hp: 10, mp: 2, atk: 2, def: 2, mag: 1, spd: 0 },
    techs: ['hammerfall', 'bulwark', 'quake', 'rally'],
    weapon: 'oath-hammer',
    armor: 'torin-vest',
    sprite: 'torin',
    portrait: 'torin',
    color: '#d7a441',
    blurb: 'A crown knight whose oath outlasted the court that gave it.',
  },
}
