import type { EnemyDef } from '../types.ts'

export const enemies: EnemyDef[] = [
  {
    id: 'gnatcoil',
    name: 'Gnatcoil',
    sprite: 'gnatcoil',
    hp: 42,
    mp: 0,
    atk: 11,
    def: 4,
    mag: 4,
    spd: 11,
    xp: 8,
    gold: 7,
    weaknesses: ['fire'],
    resists: [],
    boss: false,
    drops: [{ item: 'tonic', chance: 0.3 }],
    skills: [
      { id: 'nip', name: 'Nip', element: 'phys', power: 9, charge: 0, target: 'enemy', weight: 3 },
      {
        id: 'rust-spit',
        name: 'Rust Spit',
        element: 'phys',
        power: 8,
        charge: 0.5,
        target: 'enemy',
        weight: 1,
        status: { id: 'poison', chance: 0.35, turns: 3 },
      },
    ],
  },
  {
    id: 'briarhusk',
    name: 'Briarhusk',
    sprite: 'briarhusk',
    hp: 78,
    mp: 0,
    atk: 13,
    def: 10,
    mag: 4,
    spd: 6,
    xp: 14,
    gold: 12,
    weaknesses: ['fire'],
    resists: ['ice'],
    boss: false,
    drops: [{ item: 'tonic', chance: 0.3 }],
    skills: [
      { id: 'thrash', name: 'Thrash', element: 'phys', power: 11, charge: 0, target: 'enemy', weight: 2 },
      { id: 'thorn', name: 'Thorn', element: 'phys', power: 8, charge: 1, target: 'all-enemies', weight: 1 },
    ],
  },
  {
    id: 'clockmite',
    name: 'Clockmite',
    sprite: 'clockmite',
    hp: 48,
    mp: 0,
    atk: 10,
    def: 5,
    mag: 12,
    spd: 13,
    xp: 12,
    gold: 10,
    weaknesses: ['volt'],
    resists: [],
    boss: false,
    drops: [{ item: 'ether', chance: 0.15 }],
    skills: [
      { id: 'bite', name: 'Bite', element: 'phys', power: 9, charge: 0, target: 'enemy', weight: 2 },
      {
        id: 'slow-chime',
        name: 'Slow Chime',
        element: 'time',
        power: 6,
        charge: 1,
        target: 'enemy',
        weight: 1,
        status: { id: 'slow', chance: 1, turns: 2 },
      },
    ],
  },
  {
    id: 'pup',
    name: 'Rift Pup',
    sprite: 'hound',
    hp: 58,
    mp: 0,
    atk: 12,
    def: 5,
    mag: 4,
    spd: 12,
    xp: 14,
    gold: 10,
    weaknesses: ['fire'],
    resists: [],
    boss: false,
    skills: [
      { id: 'snap', name: 'Snap', element: 'phys', power: 10, charge: 0, target: 'enemy', weight: 1 },
    ],
  },
  {
    id: 'hound',
    name: 'Rift Hound',
    sprite: 'hound',
    hp: 230,
    mp: 0,
    atk: 16,
    def: 8,
    mag: 8,
    spd: 10,
    xp: 55,
    gold: 45,
    weaknesses: ['ice'],
    resists: ['shadow'],
    boss: true,
    drops: [{ item: 'ether', chance: 1 }],
    skills: [
      { id: 'rend', name: 'Rend', element: 'phys', power: 14, charge: 0, target: 'enemy', weight: 3 },
      {
        id: 'howl',
        name: 'Howl',
        element: 'time',
        power: 8,
        charge: 1.3,
        target: 'all-enemies',
        weight: 1,
        status: { id: 'slow', chance: 1, turns: 2 },
      },
    ],
  },
  {
    id: 'cindermote',
    name: 'Cindermote',
    sprite: 'cindermote',
    hp: 66,
    mp: 0,
    atk: 12,
    def: 6,
    mag: 14,
    spd: 12,
    xp: 16,
    gold: 14,
    weaknesses: ['ice'],
    resists: ['fire'],
    boss: false,
    drops: [{ item: 'ether', chance: 0.15 }],
    skills: [
      { id: 'cinder', name: 'Cinder', element: 'fire', power: 14, charge: 0.4, target: 'enemy', weight: 1 },
    ],
  },
  {
    id: 'acolyte',
    name: 'Rust Acolyte',
    sprite: 'acolyte',
    hp: 92,
    mp: 0,
    atk: 11,
    def: 8,
    mag: 16,
    spd: 9,
    xp: 18,
    gold: 16,
    weaknesses: ['ice'],
    resists: [],
    boss: false,
    drops: [{ item: 'tonic', chance: 0.3 }],
    skills: [
      { id: 'spark', name: 'Spark', element: 'volt', power: 14, charge: 0.6, target: 'enemy', weight: 3 },
      {
        id: 'mend-self',
        name: 'Mend Self',
        element: 'heal',
        power: 12,
        charge: 0,
        target: 'self',
        weight: 1,
        heal: true,
      },
    ],
  },
  {
    id: 'wisp',
    name: 'Gear Wisp',
    sprite: 'wisp',
    hp: 56,
    mp: 0,
    atk: 9,
    def: 4,
    mag: 15,
    spd: 15,
    xp: 15,
    gold: 12,
    weaknesses: ['phys'],
    resists: ['volt'],
    boss: false,
    drops: [{ item: 'ether', chance: 0.15 }],
    skills: [
      { id: 'grind', name: 'Grind', element: 'phys', power: 10, charge: 0, target: 'enemy', weight: 1 },
    ],
  },
  {
    id: 'saint',
    name: 'Iron Saint',
    sprite: 'saint',
    hp: 400,
    mp: 0,
    atk: 18,
    def: 14,
    mag: 16,
    spd: 8,
    xp: 90,
    gold: 80,
    weaknesses: ['volt'],
    resists: ['phys'],
    boss: true,
    drops: [{ item: 'tonic-plus', chance: 1 }],
    skills: [
      { id: 'mace', name: 'Mace', element: 'phys', power: 16, charge: 0, target: 'enemy', weight: 3 },
      {
        id: 'bell-toll',
        name: 'Bell Toll',
        element: 'shadow',
        power: 14,
        charge: 1.6,
        target: 'all-enemies',
        weight: 1,
      },
      {
        id: 'mend',
        name: 'Mend',
        element: 'heal',
        power: 14,
        charge: 1,
        target: 'self',
        weight: 1,
        heal: true,
      },
    ],
  },
  {
    id: 'wraith',
    name: 'Banner Wraith',
    sprite: 'wraith',
    hp: 100,
    mp: 0,
    atk: 15,
    def: 7,
    mag: 12,
    spd: 11,
    xp: 20,
    gold: 18,
    weaknesses: ['fire'],
    resists: [],
    boss: false,
    drops: [{ item: 'tonic', chance: 0.3 }],
    skills: [
      { id: 'drape', name: 'Drape', element: 'shadow', power: 13, charge: 0.4, target: 'enemy', weight: 1 },
    ],
  },
  {
    id: 'oath',
    name: 'Stone Oath',
    sprite: 'oath',
    hp: 140,
    mp: 0,
    atk: 16,
    def: 16,
    mag: 6,
    spd: 6,
    xp: 22,
    gold: 18,
    weaknesses: ['volt'],
    resists: ['phys'],
    boss: false,
    drops: [{ item: 'tonic', chance: 0.3 }],
    skills: [
      { id: 'slam', name: 'Slam', element: 'phys', power: 15, charge: 0.8, target: 'enemy', weight: 1 },
    ],
  },
  {
    id: 'shade',
    name: 'Crown Shade',
    sprite: 'shade',
    hp: 84,
    mp: 0,
    atk: 14,
    def: 6,
    mag: 14,
    spd: 13,
    xp: 18,
    gold: 15,
    weaknesses: ['fire'],
    resists: ['shadow'],
    boss: false,
    drops: [{ item: 'ether', chance: 0.15 }],
    skills: [
      { id: 'gnaw', name: 'Gnaw', element: 'shadow', power: 13, charge: 0, target: 'enemy', weight: 1 },
    ],
  },
  {
    id: 'minute',
    name: 'Minute Hand',
    sprite: 'minute',
    hp: 96,
    mp: 0,
    atk: 13,
    def: 6,
    mag: 8,
    spd: 15,
    xp: 12,
    gold: 0,
    weaknesses: ['phys'],
    resists: [],
    boss: false,
    skills: [
      { id: 'prick', name: 'Prick', element: 'phys', power: 12, charge: 0, target: 'enemy', weight: 1 },
    ],
  },
  {
    id: 'hour',
    name: 'Hour Hand',
    sprite: 'hour',
    hp: 280,
    mp: 0,
    atk: 22,
    def: 16,
    mag: 10,
    spd: 7,
    xp: 30,
    gold: 0,
    weaknesses: ['volt'],
    resists: ['ice'],
    boss: false,
    skills: [
      { id: 'crush', name: 'Crush', element: 'phys', power: 18, charge: 1.2, target: 'enemy', weight: 1 },
    ],
  },
  {
    id: 'stillness',
    name: 'The Stillness',
    sprite: 'stillness',
    hp: 760,
    mp: 0,
    atk: 20,
    def: 12,
    mag: 22,
    spd: 9,
    xp: 160,
    gold: 80,
    weaknesses: ['time'],
    resists: ['phys'],
    boss: true,
    skills: [
      { id: 'grasp', name: 'Grasp', element: 'shadow', power: 16, charge: 0, target: 'enemy', weight: 3 },
      {
        id: 'zero-hour',
        name: 'Zero Hour',
        element: 'time',
        power: 42,
        charge: 5,
        target: 'all-enemies',
        weight: 1,
        ultimate: true,
      },
    ],
  },
  {
    id: 'torin-spar',
    name: 'Sir Torin',
    sprite: 'torin',
    hp: 170,
    mp: 0,
    atk: 15,
    def: 11,
    mag: 6,
    spd: 9,
    xp: 40,
    gold: 0,
    weaknesses: [],
    resists: [],
    boss: true,
    skills: [
      { id: 'oath-cut', name: 'Oath Cut', element: 'phys', power: 14, charge: 0, target: 'enemy', weight: 3 },
      {
        id: 'brace',
        name: 'Brace',
        element: 'phys',
        power: 0,
        charge: 0.6,
        target: 'self',
        weight: 1,
        status: { id: 'protect', chance: 1, turns: 2 },
      },
    ],
  },
]

export const enemyById: Record<string, EnemyDef> = {}
for (const enemy of enemies) enemyById[enemy.id] = enemy
