import type { ItemDef } from '../types.ts'

export const items: ItemDef[] = [
  {
    id: 'tonic',
    name: 'Fair Tonic',
    blurb: 'A sweet cup from the stalls. Twenty marks, and it puts the color back.',
    kind: 'consumable',
    price: 20,
    hp: 50,
  },
  {
    id: 'tonic-plus',
    name: 'Ash Tonic',
    blurb: 'Thick restorative the ash market boils in a tin. Seventy marks.',
    kind: 'consumable',
    price: 70,
    hp: 140,
  },
  {
    id: 'ether',
    name: 'Spark Phial',
    blurb: 'A blue phial that steadies the hands. Forty marks.',
    kind: 'consumable',
    price: 40,
    mp: 20,
  },
  {
    id: 'elixir',
    name: 'Whole Draught',
    blurb: 'One bottle for blood and breath together. A hundred and eighty marks.',
    kind: 'consumable',
    price: 180,
    full: true,
  },
  {
    id: 'phoenix',
    name: 'Cinder Feather',
    blurb: 'Warm enough to pull someone back. Ninety marks, if the armory will sell it.',
    kind: 'consumable',
    price: 90,
    revive: true,
    hp: 40,
  },
  {
    id: 'practice-blade',
    name: 'Practice Blade',
    blurb: 'Kael\'s fairground sword, light and already nicked.',
    kind: 'weapon',
    price: 0,
    atk: 3,
    users: ['kael'],
  },
  {
    id: 'fair-sabre',
    name: 'Fair Sabre',
    blurb: 'A stall sabre with a real edge. Eighty marks.',
    kind: 'weapon',
    price: 80,
    atk: 8,
    users: ['kael'],
  },
  {
    id: 'rift-edge',
    name: 'Rift Edge',
    blurb: 'Cooled where the hound tore the wood. It hums when a second slips.',
    kind: 'weapon',
    price: 0,
    atk: 14,
    users: ['kael'],
  },
  {
    id: 'field-bow',
    name: 'Field Bow',
    blurb: 'Mira\'s traveling bow, strung for a long road.',
    kind: 'weapon',
    price: 0,
    mag: 4,
    users: ['mira'],
  },
  {
    id: 'ash-recurve',
    name: 'Ash Recurve',
    blurb: 'Heat-warped and still true. The market asks a hundred and twenty marks.',
    kind: 'weapon',
    price: 120,
    mag: 10,
    users: ['mira'],
  },
  {
    id: 'bell-bow',
    name: 'Bell Bow',
    blurb: 'Strung with wire from the Volt Bell. The draw throws a spark.',
    kind: 'weapon',
    price: 0,
    mag: 16,
    users: ['mira'],
  },
  {
    id: 'oath-hammer',
    name: 'Oath Hammer',
    blurb: 'Torin\'s hammer, the oath cut into the haft.',
    kind: 'weapon',
    price: 0,
    atk: 6,
    users: ['torin'],
  },
  {
    id: 'crown-maul',
    name: 'Crown Maul',
    blurb: 'Keep steel, heavy enough to argue with a door. A hundred and sixty marks.',
    kind: 'weapon',
    price: 160,
    atk: 14,
    users: ['torin'],
  },
  {
    id: 'kael-cloth',
    name: 'Duelist\'s Cloth',
    blurb: 'Light fair clothes that have survived more duels than they should.',
    kind: 'armor',
    price: 0,
    def: 2,
    users: ['kael'],
  },
  {
    id: 'mira-cloak',
    name: 'Ash Cloak',
    blurb: 'Travel wool gone gray. It still smells like a shut archive.',
    kind: 'armor',
    price: 0,
    def: 3,
    users: ['mira'],
  },
  {
    id: 'torin-vest',
    name: 'Oath Vest',
    blurb: 'Padded under the crown\'s colors, mended twice at the ribs.',
    kind: 'armor',
    price: 0,
    def: 5,
    users: ['torin'],
  },
  {
    id: 'leather-coat',
    name: 'Leather Coat',
    blurb: 'A stall coat. Sixty marks, and it turns a knife better than linen.',
    kind: 'armor',
    price: 60,
    def: 6,
  },
  {
    id: 'travelers-mail',
    name: 'Traveler\'s Mail',
    blurb: 'Ringmail for a road that hits back. A hundred and ten marks.',
    kind: 'armor',
    price: 110,
    def: 10,
  },
  {
    id: 'knight-plate',
    name: 'Knight Plate',
    blurb: 'Crown plate the armory is tired of polishing. A hundred and fifty marks.',
    kind: 'armor',
    price: 150,
    def: 14,
  },
  {
    id: 'verdant-mantle',
    name: 'Verdant Mantle',
    blurb: 'Woven from the tree that kept one patch of Ashspire alive across the centuries.',
    kind: 'armor',
    price: 0,
    def: 12,
    mag: 4,
  },
  {
    id: 'fuse-east',
    name: 'East Fuse',
    blurb: 'Copper-sweet and warm at one end. The cathedral\'s east socket is waiting.',
    kind: 'key',
    price: 0,
  },
  {
    id: 'fuse-west',
    name: 'West Fuse',
    blurb: 'The west fuse, heavy and impatient to be seated.',
    kind: 'key',
    price: 0,
  },
]

export const itemById: Record<string, ItemDef> = {}
for (const item of items) itemById[item.id] = item
