import type { GameMap, MapId } from '../types.ts'

export const maps: Record<MapId, GameMap> = {
  leorain: {
    id: 'leorain',
    name: 'Leorain Fair',
    era: 'present',
    music: 'town',
    rows: [
    "##############,,,,##############",
    "#ttttttttttttt,,,,ttttttttttttt#",
    "#t............,,,,............t#",
    "#t..ff........,,,,........ff..t#",
    "#t######......,,,,......######t#",
    "#t#ssss#......,,,,......#ssss#t#",
    "#t#ssss#......,,,,......#ssss#t#",
    "#t#ssssd......,,,,......dssss#t#",
    "#t######......,,,,......######t#",
    "#t............,,,,............t#",
    "#t######..ff..,,,,..ff..######t#",
    "#t#cccc#...gggggggggg...#ssss#t#",
    "#t#cccc#...ggggkggggg...#ssss#t#",
    "#t#ccccd...gggggggggg...dssss#t#",
    "#t######......,,,,......######t#",
    "#t..ff........,,,,........ff..t#",
    "#t............,,,,............t#",
    "#t............,,,,............t#",
    "#t..f......f..,,,,..f......f..t#",
    "#t............,,,,............t#",
    "#t######......,,,,......==##==t#",
    "#t#cccc#......,,,,......#sss=#t#",
    "#t#cccc#......,,,,......#sss=#t#",
    "#t#ccccd......,,,,......#sss=#t#",
    "#t######......,,,,......==dd==t#",
    "#t............,,,,............t#",
    "#tttttttttttttttttttttttttttttt#",
    "################################",
    ],
    npcs: [
      {
        id: 'mayor',
        name: 'Mayor',
        portrait: 'mayor',
        sprite: 'mayor',
        x: 4,
        y: 22,
        lines: [
          'The Clockwood is ringing hours that do not belong to today.',
          'If you take the north road, come back before dusk forgets its name.',
        ],
      },
      {
        id: 'merchant',
        name: 'Merchant',
        portrait: 'merchant',
        sprite: 'merchant',
        x: 8,
        y: 7,
        lines: [
          'Fair sabres, tonics, and a coat that has already survived one noon.',
          'If the bell strikes twice, I count the till and close.',
        ],
      },
      {
        id: 'innkeeper',
        name: 'Innkeeper',
        portrait: 'merchant',
        sprite: 'merchant',
        x: 3,
        y: 11,
        lines: [
          'Boots off if they are full of grass.',
          'The clock in the hall is fast. I stopped arguing with it.',
        ],
      },
      {
        id: 'kid',
        name: 'Kid',
        portrait: 'npc',
        sprite: 'kid',
        x: 4,
        y: 15,
        lines: [
          'The puppet stage clock hopped backward. I saw it.',
          'Father says puppets do that. The clock is not a puppet.',
        ],
      },
      {
        id: 'guard',
        name: 'Guard',
        portrait: 'npc',
        sprite: 'guard',
        x: 11,
        y: 3,
        lines: [
          'North road is open. I am not paid to argue with bells.',
          'Duel on the grass if you must. The mayor slips on cobbles.',
        ],
      },
      {
        id: 'smith',
        name: 'Smith',
        portrait: 'npc',
        sprite: 'smith',
        x: 26,
        y: 22,
        lines: [
          'Practice blades are soft so the fair can forgive you.',
          'Bring me a nicked edge and I will pretend I am busy.',
        ],
      },
    ],
    enemies: [],
    chests: [],
    warps: [
      {
        id: 'leorain-north',
        x: 14,
        y: 0,
        w: 4,
        h: 1,
        to: 'woods',
        tx: 15,
        ty: 33,
        facing: 'up',
      },
    ],
    triggers: [
      {
        id: 'intro',
        x: 15,
        y: 19,
        w: 1,
        h: 1,
        script: 'intro',
        once: true,
        unless: 'intro_done',
      },
    ],
    interacts: [
      { id: 'shop-leorain', x: 4, y: 5, kind: 'shop', shop: 'leorain' },
      { id: 'inn-leorain', x: 5, y: 12, kind: 'script', script: 'inn' },
      { id: 'save-leorain', x: 15, y: 12, kind: 'save' },
      { id: 'gate-leorain', x: 13, y: 12, kind: 'gate' },
    ],
  },
  woods: {
    id: 'woods',
    name: 'Clockwood',
    era: 'present',
    music: 'woods',
    rows: [
    "################################",
    "#ttt........................ttt#",
    "#ttt.oo............mmm......ttt#",
    "#ttt......................o.ttt#",
    "#ttt....................~~..ttt#",
    "#ttt........................ttt#",
    "#ttt..ff....................ttt#",
    "#ttt........................ttt#",
    "#==============dd==============#",
    "#ttttttttttttt,,,,ttttttttttttt#",
    "#ttt.........................tt#",
    "#tt.o........................tt#",
    "#tt..ff.........s............tt#",
    "#tt....s................s....tt#",
    "#tt.......................ff.tt#",
    "#tt........................o.tt#",
    "#ttt..ppp..............ppp...tt#",
    "#tttttpp~pppppppppppppppppttttt#",
    "#tttttppptwwwwwwwwwwwwwpppttttt#",
    "#tttttppptwwwwwwwwwwwwwpppttttt#",
    "#tttttppppbbbbbbbbbbbbbpppttttt#",
    "#tttttppptwwwwwwwwwwwwwpppttttt#",
    "#tttttppptwwwwwwwwwwwwwpppttttt#",
    "#tttttpppppppppppppppppp~pttttt#",
    "#tttttppfttttttttttttttpppttttt#",
    "#tttttpppttttttttttttttpppttttt#",
    "#tttttpppttttt,,,,,,,,,,,,ttttt#",
    "#tttttpppttttt,,,,,,,,,,,,ttttt#",
    "#tttttpppttttt,,,,ttttttttttttt#",
    "#tttttpppttttt,,,,ttttttttttttt#",
    "#ttttt,,,,,,,,,,,,ttttttttttttt#",
    "#ttttt,,,,,,,,,,,,ttttttttttttt#",
    "#ttttttttttttt,,,,ttttttttttttt#",
    "#ttttttttttttt,,,,ttttttttttttt#",
    "#ttttttttttttt,,,,ttttttttttttt#",
    "##############,,,,##############",
    ],
    npcs: [],
    enemies: [
      {
        instanceId: 'gnat-1',
        enemies: ['gnatcoil'],
        x: 7,
        y: 22,
        patrol: [{ x: 7, y: 20 }, { x: 7, y: 24 }],
        chase: true,
        boss: false,
      },
      {
        instanceId: 'gnat-2',
        enemies: ['gnatcoil'],
        x: 24,
        y: 22,
        patrol: [{ x: 24, y: 19 }, { x: 24, y: 25 }],
        chase: true,
        boss: false,
      },
      {
        instanceId: 'briar-1',
        enemies: ['briarhusk'],
        x: 7,
        y: 28,
        patrol: [{ x: 6, y: 28 }, { x: 8, y: 28 }],
        chase: true,
        boss: false,
      },
      {
        instanceId: 'briar-2',
        enemies: ['briarhusk'],
        x: 24,
        y: 26,
        patrol: [{ x: 23, y: 26 }, { x: 25, y: 26 }],
        chase: true,
        boss: false,
      },
      {
        instanceId: 'mite-1',
        enemies: ['clockmite'],
        x: 15,
        y: 26,
        patrol: [{ x: 15, y: 26 }, { x: 15, y: 27 }],
        chase: true,
        boss: false,
      },
      {
        instanceId: 'mite-2',
        enemies: ['clockmite'],
        x: 16,
        y: 17,
        patrol: [{ x: 14, y: 17 }, { x: 18, y: 17 }],
        chase: true,
        boss: false,
      },
      {
        instanceId: 'hound',
        enemies: ['hound'],
        x: 16,
        y: 3,
        patrol: [{ x: 14, y: 3 }, { x: 18, y: 3 }],
        chase: false,
        boss: true,
        victoryFlag: 'hound_dead',
      },
    ],
    chests: [
      { id: 'woods-tonic', x: 10, y: 14, item: 'tonic' },
      { id: 'woods-rift-edge', x: 22, y: 4, item: 'rift-edge' },
    ],
    warps: [
      {
        id: 'woods-south',
        x: 14,
        y: 35,
        w: 4,
        h: 1,
        to: 'leorain',
        tx: 15,
        ty: 2,
        facing: 'down',
      },
      {
        id: 'woods-alcove-in',
        x: 15,
        y: 8,
        w: 2,
        h: 1,
        to: 'woods',
        tx: 15,
        ty: 5,
        facing: 'up',
        requires: 'bells_solved',
        deny: 'The bells are out of order. Dawn, noon, dusk.',
      },
      {
        id: 'woods-alcove-out',
        x: 15,
        y: 7,
        w: 2,
        h: 1,
        to: 'woods',
        tx: 15,
        ty: 11,
        facing: 'down',
      },
    ],
    triggers: [
      {
        id: 'woods_enter',
        x: 14,
        y: 32,
        w: 4,
        h: 1,
        script: 'woods_enter',
        once: true,
      },
      {
        id: 'after_hound',
        x: 14,
        y: 3,
        w: 5,
        h: 1,
        script: 'after_hound',
        once: true,
        requires: 'hound_dead',
      },
    ],
    interacts: [
      { id: 'bell-dawn', x: 7, y: 13, kind: 'bell' },
      { id: 'bell-noon', x: 16, y: 12, kind: 'bell' },
      { id: 'bell-dusk', x: 24, y: 13, kind: 'bell' },
      {
        id: 'woods-sign',
        x: 16,
        y: 15,
        kind: 'sign',
        text: 'Dawn, then noon, then dusk. The wood remembers the order of a day.',
      },
      { id: 'chest-woods-tonic', x: 10, y: 14, kind: 'chest', chest: 'woods-tonic' },
      { id: 'chest-woods-rift', x: 22, y: 4, kind: 'chest', chest: 'woods-rift-edge' },
    ],
  },
  ashspire: {
    id: 'ashspire',
    name: 'Ashspire',
    era: 'future',
    music: 'future',
    rows: [
    "##############,,,,##############",
    "#ttttttttttttt,,,,ttttttttttttt#",
    "#taaaaaaaaaaaa,,,,aaaaaaaaaaaat#",
    "#a######aaaaaa,,,,aaaaaaaaaaaaa#",
    "#t#mmmm#aaaaaa,,,,aaaa###r##aat#",
    "#t#mmmm#aaaaaa,,,,aaaa#rrrr.aat#",
    "#a##d###aaaaaa,,,,aaaa#rrrr.aaa#",
    "#taaaaaaaaaaaa,,,,aaaarrrrr.aat#",
    "#taaaaaaaaaaaa,,,,aaaa..rr..aat#",
    "#aaaaaaaaaaaaa,,,,aa~aaaaaaaaaa#",
    "#taaaaooaaaaaa,,,,aaaaaaaaaaaat#",
    "#taaaaaammaaaa,,,,aaaaaaaaaaaat#",
    "#aaaaaaaaaraaa,,,,aaaaaaaaaaaaa#",
    "#taaaaaaaaaaggggggggaaaaaaaaaat#",
    "#taaaaaaaaaagggkggggaaaaaaaaaat#",
    "#aaaaaaaaaaaggggggggaaaaaaaaaaa#",
    "#taaaaaaaaaaaa,,,,aaaarrrrrraat#",
    "#taaaaaaaaaaaa,,,,aaaarrrrmraat#",
    "#aaaaaaaaaaaaa,,,,aaaarrmrrraaa#",
    "#taaaaaaaaaaaa,,,,aaaartrrrraat#",
    "#taaa~aaaaaaaa,,,,aaaaaaaaaaaat#",
    "#aaaa~aaaaaaaa,,,,aaaaaaaaaaaaa#",
    "#taaaaaaoaaaaa,,,,aaaaaaaaaaaat#",
    "#taaaaaaaaaaaa,,,,aaaaaaaaaaaat#",
    "#aaaaaaaaaaaaa,,,,aaaaaaaaaaaaa#",
    "#taaaaaaaaaaaa,,,,aaaaaaaaaaaat#",
    "#tttttttttttta,,,,atttttttttttt#",
    "################################",
    ],
    npcs: [
      {
        id: 'ash-survivor',
        name: 'Sera',
        portrait: 'survivor',
        sprite: 'survivor',
        x: 11,
        y: 16,
        lines: [
          'Mira Quell. You told the stacks you would be back by dark.',
          'The bell-priests nail rust to anyone still counting seconds.',
        ],
      },
      {
        id: 'ash-merchant',
        name: 'Merchant',
        portrait: 'merchant',
        sprite: 'merchant',
        x: 6,
        y: 8,
        lines: [
          'Ash tonic and mail. The marks still spend, out of habit.',
          'Do not haggle loud. The cathedral listens through the cracks.',
        ],
      },
    ],
    enemies: [
      {
        instanceId: 'cinder-1',
        enemies: ['cindermote'],
        x: 9,
        y: 20,
        patrol: [{ x: 9, y: 20 }, { x: 9, y: 21 }],
        chase: true,
        boss: false,
      },
      {
        instanceId: 'cinder-2',
        enemies: ['cindermote'],
        x: 23,
        y: 18,
        patrol: [{ x: 23, y: 18 }, { x: 25, y: 18 }],
        chase: true,
        boss: false,
      },
      {
        instanceId: 'wisp-ash',
        enemies: ['wisp'],
        x: 20,
        y: 10,
        patrol: [{ x: 20, y: 10 }, { x: 20, y: 9 }],
        chase: true,
        boss: false,
      },
    ],
    chests: [
      { id: 'ash-tonic-plus', x: 25, y: 17, item: 'tonic-plus' },
    ],
    warps: [
      {
        id: 'ash-north',
        x: 14,
        y: 0,
        w: 4,
        h: 1,
        to: 'cathedral',
        tx: 15,
        ty: 31,
        facing: 'up',
      },
    ],
    triggers: [
      {
        id: 'ash_arrive',
        x: 16,
        y: 18,
        w: 1,
        h: 1,
        script: 'ash_arrive',
        once: true,
      },
    ],
    interacts: [
      { id: 'shop-ashspire', x: 4, y: 5, kind: 'shop', shop: 'ashspire' },
      { id: 'save-ashspire', x: 15, y: 14, kind: 'save' },
      { id: 'gate-ashspire', x: 13, y: 14, kind: 'gate' },
      { id: 'chest-ash-tonic', x: 25, y: 17, kind: 'chest', chest: 'ash-tonic-plus' },
    ],
  },
  cathedral: {
    id: 'cathedral',
    name: 'Rust Cathedral',
    era: 'future',
    music: 'future',
    rows: [
    "################################",
    "###mmmmmmmmmmmccccmmmmmmmmmmm###",
    "###mmmm||mmmmmccccmmmmm||mmmm###",
    "###mmmmmmmmmmmccccmmmmmmmmmmm###",
    "###mmmm||mmmmmccccmmmmm||mmmm###",
    "###mmmmmmmmmmmccccmmmmmmmmmmm###",
    "###mmmm||mmmmmccccmmmmm||mmmm###",
    "###mmmmmmmmmmmccccmmmmmmmmmmm###",
    "###############dd###############",
    "###mmmmmmmmmmmccccmmmmmmmmmmm###",
    "###mmmmmmmmmmmccccmmmmmmmmmmm###",
    "###mmmmm|mmmmmccccmmmmm|mmmmm###",
    "###mmmmmmmmmmmcckcmmmmmmmmmmm###",
    "###mmmmmmmmmmmccccmmmmmmmmmmm###",
    "###mmmmm|mmmmmccccmmmmm|mmmmm###",
    "##########mmmmccccmmmm##########",
    "#ssssssss#mmmmccccmmmm#ssssssss#",
    "#ssssssss#mmmmccccmmmm#ssssssss#",
    "#ssssssssdmmmmccccmmmmdssssssss#",
    "#ssssssss#mmmmccccmmmm#ssssssss#",
    "#ssssssss#mmmmccccmmmm#ssssssss#",
    "##########mmmmccccmmmm##########",
    "###mmmmmmmmmmmccccmmmmmmmmmmm###",
    "###mmmmm|mmmmmccccmmmmm|mmmmm###",
    "#########mmmmmccccmmmmmmmmmmm###",
    "#sssssss#mmmmmccccmmmmmmmmmmm###",
    "#sssssssdmmmmmccccmmmmm|mmmmm###",
    "#########mmmmmccccmmmmmmmmmmm###",
    "###mmmmmmmmmmmccccmmmmmmmmmmm###",
    "###mmmmm|mmmmmccccmmmmm|mmmmm###",
    "###mmmmmmmmmmmccccmmmmmmmmmmm###",
    "###mmmmmmmmmmmccccmmmmmmmmmmm###",
    "###mmmmmmmmmmmccccmmmmmmmmmmm###",
    "##############,,,,##############",
    ],
    npcs: [
      {
        id: 'cath-priest',
        name: 'Priest',
        portrait: 'priest',
        sprite: 'priest',
        x: 6,
        y: 12,
        lines: [
          'East socket, west socket. The door ate a man who brought one.',
          'I sweep the aisle. I do not sweep the nave.',
        ],
      },
    ],
    enemies: [
      {
        instanceId: 'acolyte-1',
        enemies: ['acolyte'],
        x: 12,
        y: 19,
        patrol: [{ x: 12, y: 19 }, { x: 14, y: 19 }],
        chase: true,
        boss: false,
      },
      {
        instanceId: 'acolyte-2',
        enemies: ['acolyte'],
        x: 18,
        y: 28,
        patrol: [{ x: 18, y: 28 }, { x: 20, y: 28 }],
        chase: true,
        boss: false,
      },
      {
        instanceId: 'wisp-1',
        enemies: ['wisp'],
        x: 12,
        y: 25,
        patrol: [{ x: 12, y: 25 }, { x: 14, y: 25 }],
        chase: true,
        boss: false,
      },
      {
        instanceId: 'wisp-2',
        enemies: ['wisp'],
        x: 20,
        y: 22,
        patrol: [{ x: 20, y: 22 }, { x: 18, y: 22 }],
        chase: true,
        boss: false,
      },
      {
        instanceId: 'cinder-hall',
        enemies: ['cindermote'],
        x: 18,
        y: 16,
        patrol: [{ x: 18, y: 16 }, { x: 16, y: 16 }],
        chase: true,
        boss: false,
      },
      {
        instanceId: 'saint',
        enemies: ['saint'],
        x: 16,
        y: 3,
        patrol: [],
        chase: false,
        boss: true,
        victoryFlag: 'saint_dead',
      },
    ],
    chests: [
      { id: 'cath-fuse-west', x: 4, y: 17, item: 'fuse-west' },
      { id: 'cath-fuse-east', x: 26, y: 17, item: 'fuse-east' },
      { id: 'cath-bell-bow', x: 5, y: 5, item: 'bell-bow' },
      { id: 'cath-ether', x: 3, y: 26, item: 'ether' },
    ],
    warps: [
      {
        id: 'cath-south',
        x: 14,
        y: 33,
        w: 4,
        h: 1,
        to: 'ashspire',
        tx: 15,
        ty: 2,
        facing: 'down',
      },
      {
        id: 'cath-nave-in',
        x: 15,
        y: 8,
        w: 2,
        h: 1,
        to: 'cathedral',
        tx: 15,
        ty: 4,
        facing: 'up',
        requires: 'fuses_set',
        deny: 'The door is shut. It wants both fuses.',
      },
      {
        id: 'cath-nave-out',
        x: 15,
        y: 7,
        w: 2,
        h: 1,
        to: 'cathedral',
        tx: 15,
        ty: 10,
        facing: 'down',
      },
    ],
    triggers: [
      {
        id: 'after_saint',
        x: 16,
        y: 3,
        w: 1,
        h: 1,
        script: 'after_saint',
        once: true,
        requires: 'saint_dead',
      },
    ],
    interacts: [
      { id: 'cathedral-door', x: 16, y: 9, kind: 'script', script: 'cathedral_door' },
      { id: 'save-cathedral', x: 16, y: 12, kind: 'save' },
      { id: 'chest-fuse-west', x: 4, y: 17, kind: 'chest', chest: 'cath-fuse-west' },
      { id: 'chest-fuse-east', x: 26, y: 17, kind: 'chest', chest: 'cath-fuse-east' },
      { id: 'chest-bell-bow', x: 5, y: 5, kind: 'chest', chest: 'cath-bell-bow' },
      { id: 'chest-cath-ether', x: 3, y: 26, kind: 'chest', chest: 'cath-ether' },
    ],
  },
  crownkeep: {
    id: 'crownkeep',
    name: 'Crownkeep',
    era: 'past',
    music: 'past',
    rows: [
    "##############,,,,##############",
    "##ssssssssssssccccssssssssssss##",
    "#########sssccccccccssssssssss##",
    "##ssssss#sssccccccccsssss###ss##",
    "##ssssssdsssssccccsssssss###ss##",
    "##ssssss#|ssssccccssss|sssssss##",
    "#########sssssccccssssssssssss##",
    "##ssssssssssssccccssssssssssss##",
    "##ssssssssssssccccssssssssssss##",
    "##sssssss|ssssccccssss|sssssss##",
    "##ss##ssssssssccccssssssss##ss##",
    "##ss##ssssssssccccssssssss##ss##",
    "##ss##ssssssssccccssssssss##ss##",
    "##sssssss|ssssccccssss|sssssss##",
    "##ssssssssssssccccssssssssssss##",
    "##ssssssssssssccccssssssssssss##",
    "##ssssssssssssccccssssssssssss##",
    "##sssssss|ssssccccssss|sssssss##",
    "##ssssssssssssccccssssssssssss##",
    "##ssssssssssssccccssssssssssss##",
    "##########ssssccccssssssssssss##",
    "##sssssss#ssssccccsss#ssssssss##",
    "##sssssss#ssssccccsss#ssssssss##",
    "##sssssssdssssccccsssdssssssss##",
    "##sssssss#ssssccccsssdssssssss##",
    "##sssssss#ssssccccsss#ssssssss##",
    "##########sssscccckss#ssssssss##",
    "##ssssssssssssccccsss#ssssssss##",
    "##ssssssssssssccccssssssssssss##",
    "################################",
    ],
    npcs: [
      {
        id: 'crown-guard',
        name: 'Guard',
        portrait: 'npc',
        sprite: 'guard',
        x: 20,
        y: 24,
        lines: [
          'That coat is cut for a winter this keep has not met.',
          'Fold it. The court counts strangers by their cloth.',
        ],
      },
      {
        id: 'crown-noble',
        name: 'Noble',
        portrait: 'noble',
        sprite: 'noble',
        x: 12,
        y: 22,
        lines: [
          'Sir Torin paces the south court when the hour goes thin.',
          'He still answers a bell that has not been cast.',
        ],
      },
    ],
    enemies: [
      {
        instanceId: 'wraith-1',
        enemies: ['wraith'],
        x: 25,
        y: 22,
        patrol: [{ x: 25, y: 22 }, { x: 28, y: 22 }],
        chase: true,
        boss: false,
      },
      {
        instanceId: 'oath-1',
        enemies: ['oath'],
        x: 27,
        y: 24,
        patrol: [{ x: 27, y: 24 }, { x: 27, y: 26 }],
        chase: true,
        boss: false,
      },
      {
        instanceId: 'shade-1',
        enemies: ['shade'],
        x: 24,
        y: 25,
        patrol: [{ x: 24, y: 25 }, { x: 26, y: 25 }],
        chase: true,
        boss: false,
      },
    ],
    chests: [
      { id: 'crown-elixir', x: 4, y: 4, item: 'elixir' },
    ],
    warps: [
      {
        id: 'crown-north',
        x: 14,
        y: 0,
        w: 4,
        h: 1,
        to: 'dial',
        tx: 15,
        ty: 2,
        facing: 'down',
        requires: 'dial_open',
        deny: 'The dial stairs are dark. Torin said three, or not at all.',
      },
    ],
    triggers: [
      {
        id: 'crown_arrive',
        x: 2,
        y: 19,
        w: 28,
        h: 1,
        script: 'crown_arrive',
        once: true,
      },
    ],
    interacts: [
      { id: 'shop-crownkeep', x: 5, y: 23, kind: 'shop', shop: 'crownkeep' },
      { id: 'save-crownkeep', x: 18, y: 26, kind: 'save' },
      { id: 'gate-crownkeep', x: 12, y: 26, kind: 'gate' },
      { id: 'chest-crown-elixir', x: 4, y: 4, kind: 'chest', chest: 'crown-elixir' },
    ],
  },
  dial: {
    id: 'dial',
    name: 'The Sunken Dial',
    era: 'void',
    music: 'dial',
    rows: [
    "##############,,,,##############",
    "######ssssssss^^^^ssssssss######",
    "######ssssssss^^^^ssssssss######",
    "######ssssssss^^^^ssssssss######",
    "######ssssssss^^^^ssssssss######",
    "######ssssssss^^^^ssss^^^^######",
    "######################^^^^######",
    "######################^^^^######",
    "######################^^^^######",
    "######################^^^^######",
    "######################^^^^######",
    "######################^^^^######",
    "######################^^^^######",
    "######################^^^^######",
    "######ssssssssssssssssssss######",
    "######ssssssssssssssssssss######",
    "######ss||ssssssssssssssss######",
    "######ssssssssssssssssssss######",
    "######ssssrrssssssssssssss######",
    "######ssssssssssssssssssss######",
    "######ssssssssssssssssssss######",
    "######^^^^ssssssssssssssss######",
    "######^^^^######################",
    "######^^^^######################",
    "######^^^^######################",
    "######^^^^######################",
    "######^^^^######################",
    "######^^^^######################",
    "######^^^^######################",
    "######^^^^######################",
    "######ssssssssssssssssssss######",
    "######ssssssssssssssssssss######",
    "######ssssssssssssssss||ss######",
    "######ssssssmmssssssssssss######",
    "######ssssssssssssssssssss######",
    "######ssssssssssssssssssss######",
    "######ssssssssssssssssssss######",
    "######ssssssssssssssss^^^^######",
    "######################^^^^######",
    "######################^^^^######",
    "######################^^^^######",
    "######################^^^^######",
    "######################^^^^######",
    "######################^^^^######",
    "######################^^^^######",
    "######################^^^^######",
    "######ssssssssssssssssssss######",
    "######ssssssssssssssssssss######",
    "######ss||ssssssssssssssss######",
    "######ssssssssssssssrsssss######",
    "######ssssssssssssssssssss######",
    "######ssssssssssssssssssss######",
    "######ssssssssssssssssssss######",
    "######^^^^ssssssssssssssss######",
    "######^^^^######################",
    "######^^^^######################",
    "######^^^^######################",
    "######^^^^######################",
    "######ssssssss^^^^ssssssss######",
    "######ssssssss^^k^ssssssss######",
    "######ssssssss^^^^ssssssss######",
    "################################",
    ],
    npcs: [],
    enemies: [
      {
        instanceId: 'dial-banners',
        enemies: ['wraith', 'shade'],
        x: 12,
        y: 16,
        patrol: [{ x: 12, y: 16 }, { x: 14, y: 17 }],
        chase: false,
        boss: false,
      },
      {
        instanceId: 'dial-ash',
        enemies: ['cindermote', 'acolyte'],
        x: 18,
        y: 33,
        patrol: [{ x: 18, y: 33 }, { x: 16, y: 34 }],
        chase: false,
        boss: false,
      },
      {
        instanceId: 'dial-oath',
        enemies: ['oath'],
        x: 14,
        y: 49,
        patrol: [{ x: 14, y: 49 }, { x: 16, y: 48 }],
        chase: false,
        boss: false,
      },
      {
        instanceId: 'dial-mix',
        enemies: ['clockmite', 'gnatcoil', 'briarhusk'],
        x: 22,
        y: 58,
        patrol: [{ x: 22, y: 58 }, { x: 24, y: 58 }],
        chase: false,
        boss: false,
      },
    ],
    chests: [
      { id: 'dial-phoenix', x: 10, y: 32, item: 'phoenix' },
      { id: 'dial-elixir', x: 18, y: 50, item: 'elixir' },
      { id: 'dial-tonic-plus', x: 22, y: 59, item: 'tonic-plus' },
    ],
    warps: [
      {
        id: 'dial-top',
        x: 14,
        y: 0,
        w: 4,
        h: 1,
        to: 'crownkeep',
        tx: 16,
        ty: 3,
        facing: 'down',
      },
    ],
    triggers: [
      {
        id: 'final_intro',
        x: 6,
        y: 60,
        w: 20,
        h: 1,
        script: 'final_intro',
        once: true,
        unless: 'stillness_dead',
      },
    ],
    interacts: [
      { id: 'save-dial', x: 16, y: 59, kind: 'save' },
      { id: 'chest-dial-phoenix', x: 10, y: 32, kind: 'chest', chest: 'dial-phoenix' },
      { id: 'chest-dial-elixir', x: 18, y: 50, kind: 'chest', chest: 'dial-elixir' },
      { id: 'chest-dial-tonic', x: 22, y: 59, kind: 'chest', chest: 'dial-tonic-plus' },
    ],
  },
}
