import type { TechDef } from '../types.ts'

export const techs: TechDef[] = [
  {
    id: 'cyclone',
    name: 'Cyclone',
    blurb: 'A turning cut.',
    element: 'phys',
    power: 16,
    mp: 4,
    target: 'enemy',
    users: ['kael'],
  },
  {
    id: 'arc-slash',
    name: 'Arc Slash',
    blurb: 'Kael rakes the blade across every foe in reach.',
    element: 'phys',
    power: 12,
    mp: 7,
    target: 'all-enemies',
    users: ['kael'],
  },
  {
    id: 'sever',
    name: 'Sever',
    blurb: 'Breaks a charging strike.',
    element: 'time',
    power: 18,
    mp: 8,
    target: 'enemy',
    users: ['kael'],
    interrupt: true,
    unlockFlag: 'sever_unlocked',
  },
  {
    id: 'kindle',
    name: 'Kindle',
    blurb: 'Mira sets a scrap of rift-ash alight and throws it.',
    element: 'fire',
    power: 18,
    mp: 4,
    target: 'enemy',
    users: ['mira'],
  },
  {
    id: 'needle',
    name: 'Needle',
    blurb: 'A narrow ice point loosed from the bow.',
    element: 'ice',
    power: 18,
    mp: 5,
    target: 'enemy',
    users: ['mira'],
  },
  {
    id: 'mend',
    name: 'Mend',
    blurb: 'Warm light pulls a wound shut.',
    element: 'heal',
    power: 16,
    mp: 6,
    target: 'ally',
    users: ['mira'],
    heal: true,
  },
  {
    id: 'read',
    name: 'Read',
    blurb: 'Names a weakness.',
    element: 'time',
    power: 0,
    mp: 2,
    target: 'enemy',
    users: ['mira'],
  },
  {
    id: 'bolt',
    name: 'Bolt',
    blurb: 'A spark borrowed from the Volt Bell, aimed and spent.',
    element: 'volt',
    power: 22,
    mp: 8,
    target: 'enemy',
    users: ['mira'],
    unlockFlag: 'bolt_unlocked',
  },
  {
    id: 'hammerfall',
    name: 'Hammerfall',
    blurb: 'Torin drops the oath-hammer on a single foe.',
    element: 'phys',
    power: 20,
    mp: 5,
    target: 'enemy',
    users: ['torin'],
  },
  {
    id: 'bulwark',
    name: 'Bulwark',
    blurb: 'An oath settles over the party and blunts the next blows.',
    element: 'time',
    power: 0,
    mp: 6,
    target: 'all-allies',
    users: ['torin'],
    status: { id: 'protect', chance: 1, turns: 3 },
  },
  {
    id: 'quake',
    name: 'Quake',
    blurb: 'The hammer hits stone and the shock runs through every foe.',
    element: 'phys',
    power: 16,
    mp: 10,
    target: 'all-enemies',
    users: ['torin'],
  },
  {
    id: 'rally',
    name: 'Rally',
    blurb: 'Torin spends breath and the party finds its feet.',
    element: 'heal',
    power: 10,
    mp: 8,
    target: 'all-allies',
    users: ['torin'],
    heal: true,
  },
  {
    id: 'rift-waltz',
    name: 'Rift Waltz',
    blurb: 'Kael cuts a circle and Mira burns the air he leaves.',
    element: 'fire',
    power: 28,
    mp: 8,
    target: 'all-enemies',
    users: ['kael', 'mira'],
  },
  {
    id: 'twin-oath',
    name: 'Twin Oath',
    blurb: 'Blade and hammer land on the same count.',
    element: 'phys',
    power: 26,
    mp: 8,
    target: 'all-enemies',
    users: ['kael', 'torin'],
  },
  {
    id: 'bellfrost',
    name: 'Bellfrost',
    blurb: 'Frost rides the hammer shock and drags the foe off the beat.',
    element: 'ice',
    power: 24,
    mp: 8,
    target: 'all-enemies',
    users: ['mira', 'torin'],
    status: { id: 'slow', chance: 1, turns: 2 },
  },
  {
    id: 'clockfall',
    name: 'Clockfall',
    blurb: 'All three ages on one second.',
    element: 'time',
    power: 48,
    mp: 12,
    target: 'all-enemies',
    users: ['kael', 'mira', 'torin'],
    interrupt: true,
    unlockFlag: 'triple_ready',
  },
]

export const techById: Record<string, TechDef> = {}
for (const tech of techs) techById[tech.id] = tech
